name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  s3-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Get AWS CLI version
        run: |
          aws --version
          which aws
      - name: Upload files under build to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 ls --debug
          aws s3 cp build/* s3://${AWS_BUCKET_NAME} --recursive --debug
