name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  s3-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Get AWS CLI version
        run: |
          aws --version
          which aws
      - name: List bucket contents
        run: |
          aws s3 ls
      - name: Upload files under build to S3
        run: |
          aws s3 cp build/* s3://${AWS_BUCKET_NAME} --recursive 
          